//
//  Configuration.h
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#ifndef CarInformationAPI_Configuration_h
#define CarInformationAPI_Configuration_h

/** The base Uri for API calls */
static const NSString* Configuration_BaseUri = @"http://carinfo.acme.com";

/** The username to use with basic authentication */
/** Replace the value of BasicAuthUserName with an appropriate value */
static NSString* Configuration_BasicAuthUserName = @"TODO: Replace";

/** The password to use with basic authentication */
/** Replace the value of BasicAuthPassword with an appropriate value */
static NSString* Configuration_BasicAuthPassword = @"TODO: Replace";

#endif
