<?php
/*
 * CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'http://carinfo.acme.com';

    //The username to use with basic authentication
    //TODO: Replace the basicAuthUserName with an appropriate value
    public static $basicAuthUserName = 'TODO: Replace';

    //The password to use with basic authentication
    //TODO: Replace the basicAuthPassword with an appropriate value
    public static $basicAuthPassword = 'TODO: Replace';

}
