/*
 * CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
package io.apimatic.carinformationapilib.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CarInfoModel 
        extends java.util.Observable {

    private int model = 2014;
    private String make;
    private String regNo;
    /** GETTER
     * model of the car
     */
    @JsonGetter("Model")
    public int getModel ( ) { 
        return this.model;
    }
    
    /** SETTER
     * model of the car
     */
    @JsonSetter("Model")
    public void setModel (int value) { 
        this.model = value;
        notifyObservers(this.model);
    }
 
    /** GETTER
     * make brand of the car
     */
    @JsonGetter("Make")
    public String getMake ( ) { 
        return this.make;
    }
    
    /** SETTER
     * make brand of the car
     */
    @JsonSetter("Make")
    public void setMake (String value) { 
        this.make = value;
        notifyObservers(this.make);
    }
 
    /** GETTER
     * registration number of the car
     */
    @JsonGetter("RegNo")
    public String getRegNo ( ) { 
        return this.regNo;
    }
    
    /** SETTER
     * registration number of the car
     */
    @JsonSetter("RegNo")
    public void setRegNo (String value) { 
        this.regNo = value;
        notifyObservers(this.regNo);
    }
 
}
 