/*
 * CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
package io.apimatic.carinformationapilib.models;
import java.util.TreeMap;
public enum CarTypesEnum {
    Sedan, //TODO: Write general description for this element
    Hatchback, //TODO: Write general description for this element
    Beetle; //TODO: Write general description for this element

    private static TreeMap<Integer, CarTypesEnum> valueMap = new TreeMap<Integer, CarTypesEnum>();
    private int value;
	static {
        Sedan.value = 0;
        Hatchback.value = 1;
        Beetle.value = 2;
        valueMap.put(0, Sedan);
        valueMap.put(1, Hatchback);
        valueMap.put(2, Beetle);
    }

	/**
    * Returns the enum member associated with the given integer value
    * @return	The enum member against the given integer value */
	@com.fasterxml.jackson.annotation.JsonCreator
	public static CarTypesEnum fromInt(int toConvert) {
        return valueMap.get(toConvert);
    }

	/**
    * Returns the integer value associated with the enum member
    * @return	The integer value against enum member */
	@com.fasterxml.jackson.annotation.JsonValue
    public int value() {
        return value;
    }
} 