# This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014

module CarInformationApi
  class CarInfoModel

    # model of the car
    # @return [Numeric]
    attr_accessor :Model

    # make brand of the car
    # @return [String]
    attr_accessor :Make

    # registration number of the car
    # @return [String]
    attr_accessor :RegNo

    def initialize
    @Model = 2014
    end
    
    def method_missing (method_name)
      puts "there's no method called '#{method_name}'"
    end

  end
end