# This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014

require 'car_information_api/models/base_numeric_enum'

module CarInformationApi
  class CarTypesEnum < BaseNumericEnum

    # TODO: Write general description for this element
    enum_attr :SEDAN, 0

    # TODO: Write general description for this element
    enum_attr :HATCHBACK, 1

    # TODO: Write general description for this element
    enum_attr :BEETLE, 2

  end
end