<?php
/*
 * CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
require_once(dirname(__FILE__) . '/BaseEnum.php');

class CarTypesEnum extends BaseEnum {
    /**
     * TODO: Write general description for this element
     */
    const SEDAN = 0;

    /**
     * TODO: Write general description for this element
     */
    const HATCHBACK = 1;

    /**
     * TODO: Write general description for this element
     */
    const BEETLE = 2;

}