/*
 * CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
package io.apimatic.carinformationapilib;

public class Configuration {
    //The base Uri for API calls
    public static final String baseUri = "http://carinfo.acme.com";

    //The username to use with basic authentication
    //TODO: Replace the BasicAuthUserName with an appropriate value
    public static String basicAuthUserName = "TODO: Replace";

    //The password to use with basic authentication
    //TODO: Replace the BasicAuthPassword with an appropriate value
    public static String basicAuthPassword = "TODO: Replace";

}
