/**
 *CarInformationAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */

function CarInfoModel(){
        this.model  = 2014     
        this.make = undefined     
        this.regNo = undefined     

}

//Make instanceof work

 



/**
 *model of the car
 *
 * @return: int
 */
CarInfoModel.prototype.getModel=function(){

        return this.model;
}
    
    

CarInfoModel.prototype.setModel=function(value){
        this.model = value;
}
     
 



/**
 *make brand of the car
 *
 * @return: string
 */
CarInfoModel.prototype.getMake=function(){

        return this.make;
}
    
    

CarInfoModel.prototype.setMake=function(value){
        this.make = value;
}
     
 



/**
 *registration number of the car
 *
 * @return: string
 */
CarInfoModel.prototype.getRegNo=function(){

        return this.regNo;
}
    
    

CarInfoModel.prototype.setRegNo=function(value){
        this.regNo = value;
}
     





