/**
  *CarInformationAPILib
  *
  *This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
  */


CarInformationAPILib.factory('CarTypesEnum', function() {
    return {
   
     //TODO: Write general description for this element
    
    SEDAN : 0,

   
     //TODO: Write general description for this element
    
    HATCHBACK : 1,

   
     //TODO: Write general description for this element
    
    BEETLE : 2,

    };
});