/*
 * CarInformationAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
using System;

namespace CarInformationAPI.PCL
{
    public class Configuration
    {
        //The base Uri for API calls
        public const string BaseUri = "http://carinfo.acme.com";

        //The username to use with basic authentication
        //TODO: Replace the BasicAuthUserName with an appropriate value
        public static string BasicAuthUserName = "TODO: Replace";

        //The password to use with basic authentication
        //TODO: Replace the BasicAuthPassword with an appropriate value
        public static string BasicAuthPassword = "TODO: Replace";

    }
}