# This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014

module CarInformationApi 
  class Configuration

    # The base Uri for API calls
    BASE_URI = "http://carinfo.acme.com"

    # The username to use with basic authentication
    # TODO: Replace the basicAuthUserName with an appropriate value
    def self.basic_auth_user_name= basic_auth_user_name
      @basic_auth_user_name = basic_auth_user_name
    end

    # TODO: Replace the basicAuthUserName with an appropriate value
    def self.basic_auth_user_name
      @basic_auth_user_name
    end

    # The password to use with basic authentication
    # TODO: Replace the basicAuthPassword with an appropriate value
    def self.basic_auth_password= basic_auth_password
      @basic_auth_password = basic_auth_password
    end

    # TODO: Replace the basicAuthPassword with an appropriate value
    def self.basic_auth_password
      @basic_auth_password
    end

    def initialize
    end

  end
end
