'''
   CarInformationAPILib
 
   This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
'''

class CarInfoModel():

    def __init__(self):   
        self.model = None        
        self.make = None        
        self.regNo = None        

 
    def getModel(self): 
        '''
        model of the car

        :rtype: int
        '''
        return self.model;
    
    

    def setModel(self,value): 
        self.model = value;
     
 
    def getMake(self): 
        '''
        make brand of the car

        :rtype: string
        '''
        return self.make;
    
    

    def setMake(self,value): 
        self.make = value;
     
 
    def getRegNo(self): 
        '''
        registration number of the car

        :rtype: string
        '''
        return self.regNo;
    
    

    def setRegNo(self,value): 
        self.regNo = value;
     
 