//
//  Group1Controller.h
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIException.h"
#import "Unirest.h"
#import "CarInfoModel.h"
#import "CarTypesEnum.h"
#import "CarTypesEnumHelper.h"

@interface Group1Controller : NSObject

/**
* Completion block definition for asynchronous call to GetCarInfo */
typedef void (^CompletedGetCarInfo)(BOOL success, CarInfoModel* response, NSError* error);

/**
* TODO: type endpoint description here
* @param    regNo    Required parameter: TODO: type description here
* @param    color    Optional parameter: TODO: type description here
* @param    cartType    Optional parameter: TODO: type description here
* @param    queryParameters    Additional optional query parameters are supported by this endpoint
*/
- (void) GetCarInfoAsyncWithRegNo:(NSString*) regNo
                color:(NSString*) color
                cartType:(enum CarTypesEnum) cartType
                queryParameters:(NSDictionary*) queryParameters
                completionBlock:(CompletedGetCarInfo) onCompleted;

/**
* Completion block definition for asynchronous call to UpdateCarInfo */
typedef void (^CompletedPostUpdateCarInfo)(BOOL success, BOOL response, NSError* error);

/**
* TODO: type endpoint description here
* @param    newOwner    Required parameter: The new owner of this car
* @param    odometer    Required parameter: Current kilometers reading from odometer
* @param    fieldParameters    Additional optional form parameters are supported by this endpoint
*/
- (void) postUpdateCarInfoAsyncWithNewOwner:(NSString*) newOwner
                odometer:(int) odometer
                fieldParameters:(NSDictionary*) fieldParameters
                completionBlock:(CompletedPostUpdateCarInfo) onCompleted;

@end