/*
 * CarInformationAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CarInformationAPI.PCL;

namespace CarInformationAPI.PCL.Models
{
    public class CarInfoModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int model = 2014;
        private string make;
        private string regNo;

        /// <summary>
        /// model of the car
        /// </summary>
        [JsonProperty("Model")]
        public int Model 
        { 
            get 
            {
                return this.model; 
            } 
            set 
            {
                this.model = value;
                onPropertyChanged("Model");
            }
        }

        /// <summary>
        /// make brand of the car
        /// </summary>
        [JsonProperty("Make")]
        public string Make 
        { 
            get 
            {
                return this.make; 
            } 
            set 
            {
                this.make = value;
                onPropertyChanged("Make");
            }
        }

        /// <summary>
        /// registration number of the car
        /// </summary>
        [JsonProperty("RegNo")]
        public string RegNo 
        { 
            get 
            {
                return this.regNo; 
            } 
            set 
            {
                this.regNo = value;
                onPropertyChanged("RegNo");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 