/*
 * CarInformationAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
 */
namespace CarInformationAPI.PCL.Models
{
    public enum CarTypesEnum
    {
        Sedan = 0, //TODO: Write general description for this method
        Hatchback = 1, //TODO: Write general description for this method
        Beetle = 2, //TODO: Write general description for this method
    }
} 