'''
CarInformationAPILib
This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
'''

class Configuration :
    #The base Uri for API calls
    BASEURI = "http://carinfo.acme.com"

    #The username to use with basic authentication
    #TODO: Replace the BasicAuthUserName with an appropriate value
    basicAuthUserName = "TODO: Replace"

    #The password to use with basic authentication
    #TODO: Replace the BasicAuthPassword with an appropriate value
    basicAuthPassword = "TODO: Replace"


