# This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'car_information_api/api_helper.rb'
require 'car_information_api/api_exception.rb'
require 'car_information_api/configuration.rb'

# Controllers
require 'car_information_api/controllers/group1_controller.rb'

# Models
require 'car_information_api/models/car_info_model.rb'
require 'car_information_api/models/car_types_enum.rb'
require 'car_information_api/models/base_numeric_enum.rb'
