//
//  CarInfoModel.h
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#ifndef CARINFOMODEL
#define CARINFOMODEL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"


//protocol defined for deserialization of JSON
@protocol CarInfoModel
@end

@interface CarInfoModel : JSONModel

/**
* model of the car
*/
@property int model;

/**
* make brand of the car
*/
@property NSString* make;

/**
* registration number of the car
*/
@property NSString* regNo;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end

#endif