//
//  CarInfoModel.m
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#import "CarInfoModel.h"

@implementation CarInfoModel

/**
* model of the car
*/
@synthesize model;

/**
* make brand of the car
*/
@synthesize make;

/**
* registration number of the car
*/
@synthesize regNo;

-(id)init
{
    if (self = [super init])
    {
        self.model = 2014;
    }
    return self;
}


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"Model": @"model",
        @"Make": @"make",
        @"RegNo": @"regNo"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end