//
//  CarTypesEnum.h
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#ifndef CARTYPESENUMHELPER
#define CARTYPESENUMHELPER

#include "CarTypesEnum.h"

/**
* Helper class interface for CarTypesEnum to NSString conversion
*/
@interface CarTypesEnumHelper : NSObject

+(id) stringFromCarTypesEnum:(enum CarTypesEnum) carTypesEnum withDefault: (id) defaultValue;

+(enum CarTypesEnum) carTypesEnumFromString:(NSString*) strValue;

@end

#endif