//
//  CarTypesEnum.h
//  CarInformationAPI
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 11/01/2014
//
#ifndef CARTYPESENUM
#define CARTYPESENUM
typedef NS_ENUM(NSInteger, CarTypesEnum)
{
        SEDAN = 0, //TODO: Write general description for this method
        HATCHBACK = 1, //TODO: Write general description for this method
        BEETLE = 2, //TODO: Write general description for this method
};

#endif